module.exports = {
  devServerPort: 8010,
  destPath: "target",
  namespace: "vic",
  useReact: false,
  useTS: true,
  cssEntry: "src/styles/index.scss",
  jsEntry: "src/js/index.ts",
  jsLegacyEntry: "src/js/legacyIndex.ts",
  cdTemplatesSrc: "src/templates/",
  lsgTemplatesSrc: "src/lsg/templates/",
  cdPagesSrc: "src/pages/",
  hbsHelperSrc: "helper/handlebarsHelper/",
  lsgConfigPath: "config/config.stylemark.yaml",
  lsgIndex: "src/lsg/index.html",
  copyStaticFiles: false,
  lsgAssetsSrc: "resources",
  enableTypeCheck: false,
  autoConsoleClear: false,
};
